name: Deploy Hello World

on:
  push:
    branches:
      - main  # Run only when you push to main branch

permissions:
  contents: read
  pages: write
  id-token: write   # ðŸ‘ˆ this fixes the error

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
